### ISSUE TITLE
Handle images, definitions

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-lint-no-dead-urls#1]
Currently, only links are checked. I personally use references and definitions a lot. Maybe images need to be added too?

I suggest something like this in [`index.js`](https://github.com/davidtheclark/remark-lint-no-dead-links/blob/d9db457ba4e3d64ee4e9d6c6662e5e4a2ac5a0ff/index.js#L27):

```diff

  visit(ast, 'link', validate);
+ visit(ast, 'image', validate);
+ visit(ast, 'definition', validate);

```

**Comment by davidtheclark** [comment]
Definitely! Do you think we should change the name to `remark-lint-no-dead-urls`, then?

**Comment by wooorm** [comment]
Yeah that makes sense, buy I feel links may just be general enough to also apply to images and definitions? I'll leave it up to you!

**Comment by davidtheclark** [comment]
Added this feature and renamed the project, then release `remark-lint-no-dead-urls` v0.2.0.
