### ISSUE TITLE
Doesn't check local images?

### ISSUE THREAD

**Issue by rjhilgefort** [remarkjs/remark-lint-no-dead-urls#10]
The `README` indicates that it should check things like the following, but I'm not seeing any error. I've verified that the plugin is running by having it check a dead url and it reports that just fine.

```markdown
![](image.jpg)
[](image.jpg)
```

**Comment by wooorm** [comment]
This indeed should work. Could you share more of your setup? [Here are some tips to make an issue more actionable](https://github.com/remarkjs/remark/blob/master/contributing.md#submitting-an-issue)

**Comment by rjhilgefort** [comment]
I'm running a gatsby site, but other than that, I just have a folder that looks like:

```
-|
 |- README.md
 |- image.jpg
```

and my `README.md` just references `image.jpg` like I mentioned above. Let me know what else would be helpful. I can't afford the time to write a failing test at the moment, but can divulge other info that you think would be helpful.

**Comment by davidtheclark** [comment]
@rjhilgefort: By default, relative URLs are skipped. To check relative URLs, you need to set `gotOptions.baseUrl`; and it will check *deployed* URLs, not what's in your local filesystem. Does this apply to your situation?

(If you do want to check relative links against your local filesystem, you can try remark-validate-links.)

**Comment by rjhilgefort** [comment]
ah, okay. I say the checks for absolute paths in the README and wrongfully assumed relative would be checked as well. `validate-links` doesn't check auto-expanded images ☹️

**Comment by wooorm** [comment]
I think we should add it to validate-links!
