### ISSUE TITLE
trying to fail on redirects

### ISSUE THREAD

**Issue by markstur** [remarkjs/remark-lint-no-dead-urls#15]
I can't get this to fail on redirects.  I've tried gotOptions in my package.json and in a rc.yaml, but I can't get it to fail.  Can't find an example config for gotOptions.  Have a working example?

**Comment by davidtheclark** [comment]
@markstur I believe it's working in [the tests](https://github.com/davidtheclark/remark-lint-no-dead-urls/blob/master/test.js), but those aren't using remark CLI — if that's what your doing. Maybe this is more a question about how to set options in remark CLI?

**Comment by markstur** [comment]
yes probably the gotOptions are not getting from the cli to the plugin

**Comment by wooorm** [comment]
@markstur Could you provide examples of what you tried?

**Comment by markstur** [comment]
Sure! Mostly trying to get redirects to fail. Using this test input (REDIRECT.md below) first test redirect w/ a github repo rename (HTTP 301 in this case). Test 2 is using gotOptions.baseUrl just to see if it works (fails to fail).  So I guess I am not getting the gotOptions to work at all. Tried a lot of other things.

Using this command (the rc.yaml and REDIRECT.md follow)
$ node_modules/.bin/remark REDIRECT.md -r rc.yaml

$ cat rc.yaml
```
settings:
  output: false
  verbose: true
  gotOptions:
    followRedirect: false
    baseUrl: http://bogus/bogus/bogus
plugins:
  - remark-validate-links
  - remark-lint-no-dead-urls
```

$ cat REDIRECT.md:
```
# TEST 1: followRedirect=false
#
# Renamed repo should be a url redirect fail, right?
# if I can get gotOptions.followRedirect=false to to work

https://github.com/markstur/demoprep

# TEST 2:  baseUrl set to test relative URLs
#
# Should test /bare/url if baseUrl is set.

Jump to [step1](/bare/url)

# TEST 3: Markdown headers (works!)
# This one works (even suggests 1a)
* Jump to [step1](#step1)


## Step1a

```


Added files as attachments (w/ .txt added because github)

[REDIRECT.md.txt](https://github.com/davidtheclark/remark-lint-no-dead-urls/files/3517321/REDIRECT.md.txt)
[rc.yaml.txt](https://github.com/davidtheclark/remark-lint-no-dead-urls/files/3517322/rc.yaml.txt)

**Comment by markstur** [comment]
oops -- added backticks above so my example file isn't so shouty

**Comment by wooorm** [comment]
@markstur could you also make sure your config file is a code block with backticks? I think I'm getting where it's going wrong but it's hard because the formatting is off

**Comment by markstur** [comment]
Absolutely. Also added the files as attachments, but had to add .txt to the names.  Thanks!

**Comment by wooorm** [comment]
@markstur Ah, you need to pass options to the plugin, not generally as `settings`.

I’m not sure where you got `verbose` from.

At the bottom of [this docs](https://github.com/unifiedjs/unified-engine/blob/master/doc/configure.md#plugins) you can find some examples on how to configure plugins. They are in JSON, but I hope you can figure it out. If not, feel free to ask here for more info!

**Comment by markstur** [comment]
I had tried nesting plugin options in rc.js and rc.yml w/o any luck. Tried .json now w/ that link but still not working as above.  Here's the rc.json I tried (attached).

[rc.json.txt](https://github.com/davidtheclark/remark-lint-no-dead-urls/files/3517560/rc.json.txt)

**Comment by wooorm** [comment]
Hmm, well `remark-validate-links` does not support gotOptions (it doesn’t use got and doesn’t connect to the network), but I think your amended config:

```json
{
  "plugins": {
    "remark-validate-links": {},
    "remark-lint-no-dead-urls": {
      "gotOptions": {
        "followRedirect": false,
        "baseUrl": "http://bogus/bogus/bogus"
      }
    }
  }
}
```

...should work for this plugin. @davidtheclark any thoughts why that wouldn’t?

**Comment by davidtheclark** [comment]
It looks to me like there's a bug in the check-links dependency. Additional options should be passed to got, but it looks like they're being overwritten, instead: https://github.com/transitive-bullshit/check-links/blob/0d135df3411e7148d9c0fdf8dccc2ceac2962085/lib/check-link.js#L26-L39

**Comment by wooorm** [comment]
I raised transitive-bullshit/check-links#5 about that!

**Comment by transitive-bullshit** [comment]
This should now be fixed in `check-links` via https://github.com/transitive-bullshit/check-links/commit/6ed05365100adb9ee1b2a62d0a01b961408cb32a and released as a patch `v1.1.8`.

I think this change should propagate by default to `remark-lint-no-dead-urls`, though I'm not sure if its `package-lock` will prevent the dependency from getting updated.

**Comment by wooorm** [comment]
This should be fixes as [1.0.0 is released](https://github.com/davidtheclark/remark-lint-no-dead-urls/commit/cc0ac037b383410e70ca2422d370175efe65b638)

**Comment by karlhorky** [comment]
Nice, so this is working? Maybe we can add the example here as a recipe to the readme... (I will do this if this is acceptable)

**Comment by karlhorky** [comment]
Testing this out with this configuration block in `package.json` doesn't seem to work with `remark-lint-no-dead-urls@1.1.0`:

```
{
  "remarkConfig": {
    "plugins": [
      "remark-mdx",
      [
        "remark-lint-no-dead-urls",
        {
          "gotOptions": {
            "followRedirect": false
          }
        }
      ]
    ]
  }
}
```

Am I doing something incorrectly?

**Comment by karlhorky** [comment]
Ah no, it seems like this is not working.

`got` still resolves the promise (eg. doesn't throw), even if `followRedirect` is set to `false`:

![Screen Shot 2020-11-28 at 13 10 39](https://user-images.githubusercontent.com/1935696/100515293-47c89c00-317b-11eb-8213-053a00f3ca8d.png)

https://repl.it/@karlhorky/ChiefBountifulUtility#index.js

Example code inspired by `check-links`:

```js
const got = require('got');

const url =
  'https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Selectors';

got
  .head(url, {
    followRedirect: false,
    retry: { retries: 0 },
  })
  .then(
    (res) =>
      console.log('got HEAD promise resolved', res.statusCode) || {
        status: 'alive',
        statusCode: res.statusCode,
      },
  )
  .catch((err) => console.log('err HEAD', err));

got(url, {
  followRedirect: false,
  retry: { retries: 0 },
})
  .then(
    (res) =>
      console.log('got GET promise resolved', res.statusCode) || {
        status: 'alive',
        statusCode: res.statusCode,
      },
  )
  .catch((err) => console.log('err GET', err));
```

**Comment by karlhorky** [comment]
@davidtheclark @wooorm would you be open to re-opening this issue and receiving a PR for adding this feature?

**Edit:** I've also opened an issue on `check-links`, since this probably needs to first happen over there: https://github.com/transitive-bullshit/check-links/issues/13

**Comment by wooorm** [comment]
I don’t have the rights to administrate this repo, but I’m sure a pr is welcome!
