### ISSUE TITLE
Cache results

### ISSUE THREAD

**Issue by wooorm** [remarkjs/remark-lint-no-dead-urls#2]
This is really awesome! But it of course can take some time to check all links. I think that can be improved by:

1. Ensuring duplicate URLs in the same AST aren’t checked twice (I have an idea on how to implement that)
2. Possibly implementing some global memory object containing previously checked links. This would be useful if this rule is implemented in a text editor (such as [`linter-remark`](https://github.com/wooorm/linter-remark) for Atom). Now, if you hit save all the links are checked again, but I think we can cache previous results?

**Comment by davidtheclark** [comment]
Implemented internal and external caching in 7cca5b1.

**Comment by wooorm** [comment]
This works perfectly, awesome!
