### ISSUE TITLE
Ability to skip some urls

### ISSUE THREAD

**Issue by foray1010** [remarkjs/remark-lint-no-dead-urls#21]
Sometimes this plugin produce false alarms, mostly because some urls are private github repo url, and using `remark` will not be able to access it.

Maybe we can add an options called `skipUrlPatterns`? e.g. `{ skipUrlPatterns: "^https:\/\/github\.com\/private_org\/.+$" }`?

**Comment by transitive-bullshit** [comment]
I think this is a good idea.

Proposed impl in https://github.com/davidtheclark/remark-lint-no-dead-urls/pull/22
