### ISSUE TITLE
Fails on Live URL

### ISSUE THREAD

**Issue by karlhorky** [remarkjs/remark-lint-no-dead-urls#24]
Hi @davidtheclark, thanks for this library!

When I run this with the following MDX content...

```html
<a
  href="https://www.freecodecamp.org/news/a-beginners-guide-to-graphql-86f849ce1bec/"
  target="_blank"
>
  freeCodeCamp: A Beginner’s Guide to GraphQL
</a>
```

...it fails as in the error message below:

```
$ yarn remark index.md
index.md
  2:9-2:86  warning  Link to https://www.freecodecamp.org/news/a-beginners-guide-to-graphql-86f849ce1bec/" is dead  no-dead-urls  remark-lint

⚠ 1 warning
```

`remark-lint-no-dead-urls` appears to be taking the `"` at the end along with the link.

cc @wooorm

**Comment by karlhorky** [comment]
Ahh, sorry, just realized that this is an incompatibility between Markdown and MDX.

Markdown does not allow for that syntax (at least on https://markdownlivepreview.com/):

![Screen Shot 2020-08-13 at 15 24 25](https://user-images.githubusercontent.com/1935696/90139843-2c2ab880-dd79-11ea-9985-271c7f501d9d.png)

I guess that it wouldn't make sense for `remark` to support this.

I will see what I can do with `gotOptions` or something...

Closing.

**Comment by wooorm** [comment]
Ah yeah, HTML like this is not supported by Markdown. See [CommonMark](https://spec.commonmark.org/dingus/?text=%3Ca%0A%20%20href%3D%22https%3A%2F%2Fwww.freecodecamp.org%2Fnews%2Fa-beginners-guide-to-graphql-86f849ce1bec%2F%22%0A%20%20target%3D%22_blank%22%0A%3E%0A%20%20freeCodeCamp%3A%20A%20Beginner’s%20Guide%20to%20GraphQL%0A%3C%2Fa%3E). So the URL, in GFM, is seen as an actual URL.

If you want to ignore MDX, you can use the `remark-mdx` plugin. Although it won’t check `href` props

**Comment by karlhorky** [comment]
Right, thanks for the explanation 👍

I'm looking to lint all of my `.mdx` files for broken links, don't have any `.md` files at the moment...

Hm, maybe [`eslint-mdx`](https://github.com/mdx-js/eslint-mdx) will be helpful.

**Edit:** ah, maybe not: https://github.com/mdx-js/eslint-mdx/issues/203

**Comment by karlhorky** [comment]
Hmm... I guess I'll use [`patch-package`](https://github.com/ds300/patch-package) to remove the `"` from the end of `node.url`. 😅

**Comment by wooorm** [comment]
why not use remark-mdx?

**Comment by karlhorky** [comment]
Hm, maybe I misunderstood your comment above:

> If you want to ignore MDX, you can use the `remark-mdx` plugin. Although it won’t check `href` props

I don't want to ignore MDX - I want to check it :)

**Comment by karlhorky** [comment]
Looking at [`remark-mdx`](https://github.com/mdx-js/mdx/tree/master/packages/remark-mdx), can't tell - does it work with `remark-lint` and `remark-cli`?

**Edit:** I guess it does - my `package.json`:

```json
{
  "remarkConfig": {
    "plugins": [
      "remark-mdx",
      "remark-lint-no-dead-urls"
    ]
  }
}
```

**Comment by wooorm** [comment]
> I don't want to ignore MDX - I want to check it :)

Well, this plugin works on markdown syntax. remark-mdx makes sure MDX is understood, but it’s still a different syntax that isn’t markdown. I don’t think there exists a project like remark-lint-no-dead-links for MDX. Would `<Icon src="...">` also be checked? Etc., many new problems!

**Comment by karlhorky** [comment]
Ah, understood. So the links in format of `<a href=""></a>` are not recognized as a `link` with a `node.url` by `remark-mdx`, I suppose...

**Comment by wooorm** [comment]
That is correct, remark/markdown does not understand HTML. And while MDX understands JSX, it does not map JSX to “equivalents” in Markdown.
