### ISSUE TITLE
Support links to private repos

### ISSUE THREAD

**Issue by nkakouros** [remarkjs/remark-lint-no-dead-urls#49]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I have a link in my README that points to the wiki of a private repo, e.g. `https://github.com/remarkjs/remark-lint-no-dead-urls/wiki`. This link is reported as dead. 

### Solution

It would be nice to have the option to supply a github token or a general authentication token to be used when accessing urls.

### Alternatives

The only alternative is to blacklist the private repo.

**Comment by wooorm** [comment]
I don't see how; this project isn't specific to GH, but the entire web. You'd need to allow tokens and login flows for all websites ever.
Instead: this seems quite logical. Other people who would view your readme would not be able to see that page either.
I'd recommend not linking to it.
Or if you do, you'd have to ignore it, and should likely write it text that it is private?

**Comment by nkakouros** [comment]
I see. I'll probably add a skip pattern for these links.
