### ISSUE TITLE
Command line (cli) usage

### ISSUE THREAD

**Issue by dialex** [remarkjs/remark-lint-no-dead-urls#5]
Can I install and use this app as a standalone command, like I can for [emark-validate-links](https://github.com/remarkjs/remark-validate-links)?

The README is not clear on what I need to do/install/configure to start using this.

**Comment by davidtheclark** [comment]
@dialex: You should be able to use it in the same way as other remark-lint plugins — same as for remark-validate-links. So the docs at https://github.com/remarkjs/remark-lint apply. If there's anything you think would be helpful to add to the docs, PR welcome!
