### ISSUE TITLE
warns but does not error

### ISSUE THREAD

**Issue by tomdavidson** [remarkjs/remark-lint-no-dead-urls#6]
I am missing something because I only get a warn from a dead URL and not an error

```shell
data/test.md
  5:1-5:33  warning  Link to http://localhost:99000 is dead  no-dead-urls  remark-lint
```

**Comment by wooorm** [comment]
You can use the `--frail` flag on remark cli to make warnings exit the build fatally.

**Comment by tomdavidson** [comment]
Thank you, I did not know of `--frail` - this will require a separate config and invocation just for no-dead-URLs (I do not want to fail on a few of my other rules), but is completely doable.

**Comment by wooorm** [comment]
You can also do any of this to modify how `no-dead-urls` works? https://github.com/remarkjs/remark-lint/blob/master/doc/rules.md#configuration

**Comment by davidtheclark** [comment]
Closing, as this seems to be resolved, and DX improvements would be to remark-lint rather than this library.

**Comment by GitMurf** [comment]
> You can use the `--frail` flag on remark cli to make warnings exit the build fatally.

@wooorm is there a way to set in `.remarkrc.cjs` for all rules from remark-lint to by default start as errors instead of warnings? Thanks!

**Comment by wooorm** [comment]
No, there is no way to do that.
Why do you want that? Because `--frail` is the better alternative. Errors in unified are for syntax errors, not for warnings about preferring some other style. But `--frail` is for your CI.

**Comment by GitMurf** [comment]
@wooorm because I leverage remark-lint with the eslint mdx plugin. We want all our linter plugins to be errors and not warnings, otherwise developers tend to ignore warnings and they build up. We want to ensure everything is uniform and enforcing eslint rules as errors (instead of warnings) is a fairly common practice to ensure all developers are complying with the lint rules.

**Comment by wooorm** [comment]
That sounds like an eslint(-mdx) problem. You’re free to use ESLint but that’s a different project that only focusses on linting. unified does more than just linting.
